# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Base info
mc_version=1.20.4
neo_version=20.4.232
neogradle.subsystems.parchment.minecraftVersion=1.20.4
neogradle.subsystems.parchment.mappingsVersion=2024.02.25
mod_group=com.mrbysco.chunkymcchunkface
mod_id=chunkymcchunkface
mod_archive_name=ChunkyMcChunkFace

#Publishing
mod_name=Chunky McChunkFace
curseforge_id=863330
modrinth_id=ZMlYNR0S

# Version
version=0.3.4

# Dependencies
jei_version=17.3.0.49
