# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=26.1.1
neo_version=26.1.1.11-beta
mod_group=com.mrbysco.chunkymcchunkface
mod_id=chunkymcchunkface
mod_archive_name=ChunkyMcChunkFace

#Publishing
mod_name=Chunky McChunkFace
curseforge_id=863330
modrinth_id=ZMlYNR0S

# Version
version=0.9.0

# Dependencies
jei_minecraft=26.1.1
jei_version=29.4.0.23
jade_id=7886513