# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.5
neo_version=21.5.88
neogradle.subsystems.parchment.minecraftVersion=1.21.5
neogradle.subsystems.parchment.mappingsVersion=2025.06.15
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.chunkymcchunkface
mod_id=chunkymcchunkface
mod_archive_name=ChunkyMcChunkFace

#Publishing
mod_name=Chunky McChunkFace
curseforge_id=863330
modrinth_id=ZMlYNR0S

# Version
version=0.6.0

# Dependencies
jei_minecraft=1.21.5
jei_version=21.4.0.27
