modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Chunky-McChunkFace/issues"
license="MIT"

[[mods]]
modId="chunkymcchunkface"
version="${file.jarVersion}"
displayName="Chunky McChunkFace"
displayURL="https://www.curseforge.com/minecraft/mc-mods/Chunky-McChunkFace"
authors="Mrbysco, ShyNieke"
credits="Douwsky for suggesting me to make this mod"
description='''
A mod that adds chunkloaders that can be activated to stay active for as long as the player is online and some time after they log off.
'''
[[dependencies.chunkymcchunkface]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.chunkymcchunkface]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"