modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Mrbysco/Chunky-McChunkFace/issues"
license="MIT"

[[mods]]
modId="chunkymcchunkface"
version="${file.jarVersion}"
displayName="Chunky McChunkFace"
displayURL="https://www.curseforge.com/minecraft/mc-mods/Chunky-McChunkFace"
authors="Mrbysco, ShyNieke"
credits="Douwsky for suggesting me to make this mod"
description='''
A mod that adds chunkloaders that can be activated to stay active for as long as the player is online and some time after they log off.
'''
[[dependencies.chunkymcchunkface]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.chunkymcchunkface]]
modId="forge"
mandatory=true
versionRange="[45.1.0,)"
ordering="NONE"
side="BOTH"